package com.cms.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table cms_admin_auth
 */
public class CmsAdminAuth implements Serializable {
    /**
     * Database Column Remarks:
     *   ????
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_admin_auth.cms_admin_id
     *
     * @mbg.generated
     */
    private Integer cmsAdminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_admin_auth.cms_admin_rid
     *
     * @mbg.generated
     */
    private Integer cmsAdminRid;

    /**
     * Database Column Remarks:
     *   ???????8-16¦Ë??????+???
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_admin_auth.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_admin_auth.version
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_admin_auth.creator
     *
     * @mbg.generated
     */
    private Integer creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_admin_auth.updator
     *
     * @mbg.generated
     */
    private Integer updator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_admin_auth.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_admin_auth.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cms_admin_auth
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_admin_auth.cms_admin_id
     *
     * @return the value of cms_admin_auth.cms_admin_id
     *
     * @mbg.generated
     */
    public Integer getCmsAdminId() {
        return cmsAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_admin_auth.cms_admin_id
     *
     * @param cmsAdminId the value for cms_admin_auth.cms_admin_id
     *
     * @mbg.generated
     */
    public void setCmsAdminId(Integer cmsAdminId) {
        this.cmsAdminId = cmsAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_admin_auth.cms_admin_rid
     *
     * @return the value of cms_admin_auth.cms_admin_rid
     *
     * @mbg.generated
     */
    public Integer getCmsAdminRid() {
        return cmsAdminRid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_admin_auth.cms_admin_rid
     *
     * @param cmsAdminRid the value for cms_admin_auth.cms_admin_rid
     *
     * @mbg.generated
     */
    public void setCmsAdminRid(Integer cmsAdminRid) {
        this.cmsAdminRid = cmsAdminRid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_admin_auth.password
     *
     * @return the value of cms_admin_auth.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_admin_auth.password
     *
     * @param password the value for cms_admin_auth.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_admin_auth.version
     *
     * @return the value of cms_admin_auth.version
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_admin_auth.version
     *
     * @param version the value for cms_admin_auth.version
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_admin_auth.creator
     *
     * @return the value of cms_admin_auth.creator
     *
     * @mbg.generated
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_admin_auth.creator
     *
     * @param creator the value for cms_admin_auth.creator
     *
     * @mbg.generated
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_admin_auth.updator
     *
     * @return the value of cms_admin_auth.updator
     *
     * @mbg.generated
     */
    public Integer getUpdator() {
        return updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_admin_auth.updator
     *
     * @param updator the value for cms_admin_auth.updator
     *
     * @mbg.generated
     */
    public void setUpdator(Integer updator) {
        this.updator = updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_admin_auth.create_time
     *
     * @return the value of cms_admin_auth.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_admin_auth.create_time
     *
     * @param createTime the value for cms_admin_auth.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_admin_auth.update_time
     *
     * @return the value of cms_admin_auth.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_admin_auth.update_time
     *
     * @param updateTime the value for cms_admin_auth.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}