package com.cms.pojo;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table cms_call_info
 */
public class CmsCallInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_call_info.cms_call_id
     *
     * @mbg.generated
     */
    private Integer cmsCallId;

    /**
     * Database Column Remarks:
     *   0??????
     *               1?????
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_call_info.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_call_info.begin_time
     *
     * @mbg.generated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date beginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_call_info.stop_time
     *
     * @mbg.generated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date stopTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_call_info.call_duration
     *
     * @mbg.generated
     */
    private Integer callDuration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_call_info.from_id
     *
     * @mbg.generated
     */
    private Integer fromId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_call_info.to_id
     *
     * @mbg.generated
     */
    private Integer toId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cms_call_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_call_info.cms_call_id
     *
     * @return the value of cms_call_info.cms_call_id
     *
     * @mbg.generated
     */
    public Integer getCmsCallId() {
        return cmsCallId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_call_info.cms_call_id
     *
     * @param cmsCallId the value for cms_call_info.cms_call_id
     *
     * @mbg.generated
     */
    public void setCmsCallId(Integer cmsCallId) {
        this.cmsCallId = cmsCallId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_call_info.type
     *
     * @return the value of cms_call_info.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_call_info.type
     *
     * @param type the value for cms_call_info.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_call_info.begin_time
     *
     * @return the value of cms_call_info.begin_time
     *
     * @mbg.generated
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_call_info.begin_time
     *
     * @param beginTime the value for cms_call_info.begin_time
     *
     * @mbg.generated
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_call_info.stop_time
     *
     * @return the value of cms_call_info.stop_time
     *
     * @mbg.generated
     */
    public Date getStopTime() {
        return stopTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_call_info.stop_time
     *
     * @param stopTime the value for cms_call_info.stop_time
     *
     * @mbg.generated
     */
    public void setStopTime(Date stopTime) {
        this.stopTime = stopTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_call_info.call_duration
     *
     * @return the value of cms_call_info.call_duration
     *
     * @mbg.generated
     */
    public Integer getCallDuration() {
        return callDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_call_info.call_duration
     *
     * @param callDuration the value for cms_call_info.call_duration
     *
     * @mbg.generated
     */
    public void setCallDuration(Integer callDuration) {
        this.callDuration = callDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_call_info.from_id
     *
     * @return the value of cms_call_info.from_id
     *
     * @mbg.generated
     */
    public Integer getFromId() {
        return fromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_call_info.from_id
     *
     * @param fromId the value for cms_call_info.from_id
     *
     * @mbg.generated
     */
    public void setFromId(Integer fromId) {
        this.fromId = fromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_call_info.to_id
     *
     * @return the value of cms_call_info.to_id
     *
     * @mbg.generated
     */
    public Integer getToId() {
        return toId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_call_info.to_id
     *
     * @param toId the value for cms_call_info.to_id
     *
     * @mbg.generated
     */
    public void setToId(Integer toId) {
        this.toId = toId;
    }
}