package com.cms.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table cms_customer_cost
 */
public class CmsCustomerCost implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_customer_cost.cms_cc_id
     *
     * @mbg.generated
     */
    private Integer cmsCcId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_customer_cost.cms_cc_rid
     *
     * @mbg.generated
     */
    private Integer cmsCcRid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_customer_cost.balance
     *
     * @mbg.generated
     */
    private Float balance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_customer_cost.overdraft
     *
     * @mbg.generated
     */
    private Float overdraft;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_customer_cost.cms_cc_plan_id
     *
     * @mbg.generated
     */
    private CmsPlan cmsPlan;

    public CmsPlan getCmsPlan() {
		return cmsPlan;
	}

	public void setCmsPlan(CmsPlan cmsPlan) {
		this.cmsPlan = cmsPlan;
	}
	
	private Integer cmsCcPlanId;
	
	

	public Integer getCmsCcPlanId() {
		return cmsCcPlanId;
	}

	public void setCmsCcPlanId(Integer cmsCcPlanId) {
		this.cmsCcPlanId = cmsCcPlanId;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_customer_cost.cms_cc_rank_id
     *
     * @mbg.generated
     */
    private Integer cmsCcRankId;

    /**
     * Database Column Remarks:
     *   ??????????????????????????��???????????????????????
     *               0????????
     *               1???????
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_customer_cost.customer_type
     *
     * @mbg.generated
     */
    private String customerType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_customer_cost.version
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_customer_cost.cms_cc_creator
     *
     * @mbg.generated
     */
    private Integer cmsCcCreator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_customer_cost.cms_cc_updator
     *
     * @mbg.generated
     */
    private Integer cmsCcUpdator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_customer_cost.cms_cc_creat_time
     *
     * @mbg.generated
     */
    private Date cmsCcCreatTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_customer_cost.cms_cc_update_time
     *
     * @mbg.generated
     */
    private Date cmsCcUpdateTime;

    /**
     * Database Column Remarks:
     *   0??????
     *               1:???????
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_customer_cost.delete_sign
     *
     * @mbg.generated
     */
    private String deleteSign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cms_customer_cost
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_customer_cost.cms_cc_id
     *
     * @return the value of cms_customer_cost.cms_cc_id
     *
     * @mbg.generated
     */
    public Integer getCmsCcId() {
        return cmsCcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_customer_cost.cms_cc_id
     *
     * @param cmsCcId the value for cms_customer_cost.cms_cc_id
     *
     * @mbg.generated
     */
    public void setCmsCcId(Integer cmsCcId) {
        this.cmsCcId = cmsCcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_customer_cost.cms_cc_rid
     *
     * @return the value of cms_customer_cost.cms_cc_rid
     *
     * @mbg.generated
     */
    public Integer getCmsCcRid() {
        return cmsCcRid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_customer_cost.cms_cc_rid
     *
     * @param cmsCcRid the value for cms_customer_cost.cms_cc_rid
     *
     * @mbg.generated
     */
    public void setCmsCcRid(Integer cmsCcRid) {
        this.cmsCcRid = cmsCcRid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_customer_cost.balance
     *
     * @return the value of cms_customer_cost.balance
     *
     * @mbg.generated
     */
    public Float getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_customer_cost.balance
     *
     * @param balance the value for cms_customer_cost.balance
     *
     * @mbg.generated
     */
    public void setBalance(Float balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_customer_cost.overdraft
     *
     * @return the value of cms_customer_cost.overdraft
     *
     * @mbg.generated
     */
    public Float getOverdraft() {
        return overdraft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_customer_cost.overdraft
     *
     * @param overdraft the value for cms_customer_cost.overdraft
     *
     * @mbg.generated
     */
    public void setOverdraft(Float overdraft) {
        this.overdraft = overdraft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_customer_cost.cms_cc_plan_id
     *
     * @return the value of cms_customer_cost.cms_cc_plan_id
     *
     * @mbg.generated
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_customer_cost.cms_cc_plan_id
     *
     * @param cmsCcPlanId the value for cms_customer_cost.cms_cc_plan_id
     *
     * @mbg.generated
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_customer_cost.cms_cc_rank_id
     *
     * @return the value of cms_customer_cost.cms_cc_rank_id
     *
     * @mbg.generated
     */
    public Integer getCmsCcRankId() {
        return cmsCcRankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_customer_cost.cms_cc_rank_id
     *
     * @param cmsCcRankId the value for cms_customer_cost.cms_cc_rank_id
     *
     * @mbg.generated
     */
    public void setCmsCcRankId(Integer cmsCcRankId) {
        this.cmsCcRankId = cmsCcRankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_customer_cost.customer_type
     *
     * @return the value of cms_customer_cost.customer_type
     *
     * @mbg.generated
     */
    public String getCustomerType() {
        return customerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_customer_cost.customer_type
     *
     * @param customerType the value for cms_customer_cost.customer_type
     *
     * @mbg.generated
     */
    public void setCustomerType(String customerType) {
        this.customerType = customerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_customer_cost.version
     *
     * @return the value of cms_customer_cost.version
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_customer_cost.version
     *
     * @param version the value for cms_customer_cost.version
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_customer_cost.cms_cc_creator
     *
     * @return the value of cms_customer_cost.cms_cc_creator
     *
     * @mbg.generated
     */
    public Integer getCmsCcCreator() {
        return cmsCcCreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_customer_cost.cms_cc_creator
     *
     * @param cmsCcCreator the value for cms_customer_cost.cms_cc_creator
     *
     * @mbg.generated
     */
    public void setCmsCcCreator(Integer cmsCcCreator) {
        this.cmsCcCreator = cmsCcCreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_customer_cost.cms_cc_updator
     *
     * @return the value of cms_customer_cost.cms_cc_updator
     *
     * @mbg.generated
     */
    public Integer getCmsCcUpdator() {
        return cmsCcUpdator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_customer_cost.cms_cc_updator
     *
     * @param cmsCcUpdator the value for cms_customer_cost.cms_cc_updator
     *
     * @mbg.generated
     */
    public void setCmsCcUpdator(Integer cmsCcUpdator) {
        this.cmsCcUpdator = cmsCcUpdator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_customer_cost.cms_cc_creat_time
     *
     * @return the value of cms_customer_cost.cms_cc_creat_time
     *
     * @mbg.generated
     */
    public Date getCmsCcCreatTime() {
        return cmsCcCreatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_customer_cost.cms_cc_creat_time
     *
     * @param cmsCcCreatTime the value for cms_customer_cost.cms_cc_creat_time
     *
     * @mbg.generated
     */
    public void setCmsCcCreatTime(Date cmsCcCreatTime) {
        this.cmsCcCreatTime = cmsCcCreatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_customer_cost.cms_cc_update_time
     *
     * @return the value of cms_customer_cost.cms_cc_update_time
     *
     * @mbg.generated
     */
    public Date getCmsCcUpdateTime() {
        return cmsCcUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_customer_cost.cms_cc_update_time
     *
     * @param cmsCcUpdateTime the value for cms_customer_cost.cms_cc_update_time
     *
     * @mbg.generated
     */
    public void setCmsCcUpdateTime(Date cmsCcUpdateTime) {
        this.cmsCcUpdateTime = cmsCcUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_customer_cost.delete_sign
     *
     * @return the value of cms_customer_cost.delete_sign
     *
     * @mbg.generated
     */
    public String getDeleteSign() {
        return deleteSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_customer_cost.delete_sign
     *
     * @param deleteSign the value for cms_customer_cost.delete_sign
     *
     * @mbg.generated
     */
    public void setDeleteSign(String deleteSign) {
        this.deleteSign = deleteSign;
    }
}