package com.cms.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table cms_customer_info
 */
public class CmsCustomerInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_customer_info.cms_id
     *
     * @mbg.generated
     */
    private Integer cmsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_customer_info.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_customer_info.idcard_num
     *
     * @mbg.generated
     */
    private String idcardNum;

    /**
     * Database Column Remarks:
     *   ??????
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_customer_info.age
     *
     * @mbg.generated
     */
    private String age;

    /**
     * Database Column Remarks:
     *   ???0??§µ?1??
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_customer_info.sex
     *
     * @mbg.generated
     */
    private String sex;

    /**
     * Database Column Remarks:
     *   ?????????7-11¦Ë
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_customer_info.landline
     *
     * @mbg.generated
     */
    private String landline;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_customer_info.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_customer_info.version
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_customer_info.creator
     *
     * @mbg.generated
     */
    private Integer creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_customer_info.updator
     *
     * @mbg.generated
     */
    private Integer updator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_customer_info.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_customer_info.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   0??????
     *               1?????
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_customer_info.delete_sign
     *
     * @mbg.generated
     */
    private String deleteSign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cms_customer_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_customer_info.cms_id
     *
     * @return the value of cms_customer_info.cms_id
     *
     * @mbg.generated
     */
    public Integer getCmsId() {
        return cmsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_customer_info.cms_id
     *
     * @param cmsId the value for cms_customer_info.cms_id
     *
     * @mbg.generated
     */
    public void setCmsId(Integer cmsId) {
        this.cmsId = cmsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_customer_info.name
     *
     * @return the value of cms_customer_info.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_customer_info.name
     *
     * @param name the value for cms_customer_info.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_customer_info.idcard_num
     *
     * @return the value of cms_customer_info.idcard_num
     *
     * @mbg.generated
     */
    public String getIdcardNum() {
        return idcardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_customer_info.idcard_num
     *
     * @param idcardNum the value for cms_customer_info.idcard_num
     *
     * @mbg.generated
     */
    public void setIdcardNum(String idcardNum) {
        this.idcardNum = idcardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_customer_info.age
     *
     * @return the value of cms_customer_info.age
     *
     * @mbg.generated
     */
    public String getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_customer_info.age
     *
     * @param age the value for cms_customer_info.age
     *
     * @mbg.generated
     */
    public void setAge(String age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_customer_info.sex
     *
     * @return the value of cms_customer_info.sex
     *
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_customer_info.sex
     *
     * @param sex the value for cms_customer_info.sex
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_customer_info.landline
     *
     * @return the value of cms_customer_info.landline
     *
     * @mbg.generated
     */
    public String getLandline() {
        return landline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_customer_info.landline
     *
     * @param landline the value for cms_customer_info.landline
     *
     * @mbg.generated
     */
    public void setLandline(String landline) {
        this.landline = landline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_customer_info.address
     *
     * @return the value of cms_customer_info.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_customer_info.address
     *
     * @param address the value for cms_customer_info.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_customer_info.version
     *
     * @return the value of cms_customer_info.version
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_customer_info.version
     *
     * @param version the value for cms_customer_info.version
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_customer_info.creator
     *
     * @return the value of cms_customer_info.creator
     *
     * @mbg.generated
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_customer_info.creator
     *
     * @param creator the value for cms_customer_info.creator
     *
     * @mbg.generated
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_customer_info.updator
     *
     * @return the value of cms_customer_info.updator
     *
     * @mbg.generated
     */
    public Integer getUpdator() {
        return updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_customer_info.updator
     *
     * @param updator the value for cms_customer_info.updator
     *
     * @mbg.generated
     */
    public void setUpdator(Integer updator) {
        this.updator = updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_customer_info.create_time
     *
     * @return the value of cms_customer_info.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_customer_info.create_time
     *
     * @param createTime the value for cms_customer_info.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_customer_info.update_time
     *
     * @return the value of cms_customer_info.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_customer_info.update_time
     *
     * @param updateTime the value for cms_customer_info.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_customer_info.delete_sign
     *
     * @return the value of cms_customer_info.delete_sign
     *
     * @mbg.generated
     */
    public String getDeleteSign() {
        return deleteSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_customer_info.delete_sign
     *
     * @param deleteSign the value for cms_customer_info.delete_sign
     *
     * @mbg.generated
     */
    public void setDeleteSign(String deleteSign) {
        this.deleteSign = deleteSign;
    }
}