package com.cms.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table cms_payment_history
 */
public class CmsPaymentHistory implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_payment_history.cms_ph_id
     *
     * @mbg.generated
     */
    private Integer cmsPhId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_payment_history.cms_ph_rid
     *
     * @mbg.generated
     */
    private Integer cmsPhRid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_payment_history.cms_ph_money
     *
     * @mbg.generated
     */
    private Float cmsPhMoney;

    /**
     * Database Column Remarks:
     *   0????????
     *               1?????????
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_payment_history.cms_ph_type
     *
     * @mbg.generated
     */
    private String cmsPhType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_payment_history.cms_ph_time
     *
     * @mbg.generated
     */
    private Date cmsPhTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cms_payment_history
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_payment_history.cms_ph_id
     *
     * @return the value of cms_payment_history.cms_ph_id
     *
     * @mbg.generated
     */
    public Integer getCmsPhId() {
        return cmsPhId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_payment_history.cms_ph_id
     *
     * @param cmsPhId the value for cms_payment_history.cms_ph_id
     *
     * @mbg.generated
     */
    public void setCmsPhId(Integer cmsPhId) {
        this.cmsPhId = cmsPhId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_payment_history.cms_ph_rid
     *
     * @return the value of cms_payment_history.cms_ph_rid
     *
     * @mbg.generated
     */
    public Integer getCmsPhRid() {
        return cmsPhRid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_payment_history.cms_ph_rid
     *
     * @param cmsPhRid the value for cms_payment_history.cms_ph_rid
     *
     * @mbg.generated
     */
    public void setCmsPhRid(Integer cmsPhRid) {
        this.cmsPhRid = cmsPhRid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_payment_history.cms_ph_money
     *
     * @return the value of cms_payment_history.cms_ph_money
     *
     * @mbg.generated
     */
    public Float getCmsPhMoney() {
        return cmsPhMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_payment_history.cms_ph_money
     *
     * @param cmsPhMoney the value for cms_payment_history.cms_ph_money
     *
     * @mbg.generated
     */
    public void setCmsPhMoney(Float cmsPhMoney) {
        this.cmsPhMoney = cmsPhMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_payment_history.cms_ph_type
     *
     * @return the value of cms_payment_history.cms_ph_type
     *
     * @mbg.generated
     */
    public String getCmsPhType() {
        return cmsPhType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_payment_history.cms_ph_type
     *
     * @param cmsPhType the value for cms_payment_history.cms_ph_type
     *
     * @mbg.generated
     */
    public void setCmsPhType(String cmsPhType) {
        this.cmsPhType = cmsPhType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_payment_history.cms_ph_time
     *
     * @return the value of cms_payment_history.cms_ph_time
     *
     * @mbg.generated
     */
    public Date getCmsPhTime() {
        return cmsPhTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_payment_history.cms_ph_time
     *
     * @param cmsPhTime the value for cms_payment_history.cms_ph_time
     *
     * @mbg.generated
     */
    public void setCmsPhTime(Date cmsPhTime) {
        this.cmsPhTime = cmsPhTime;
    }
}