package com.cms.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table cms_product_purchase_time
 */
public class CmsProductPurchaseTime implements Serializable {
    /**
     * Database Column Remarks:
     *   ????
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_product_purchase_time.cms_ppt_id
     *
     * @mbg.generated
     */
    private Integer cmsPptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_product_purchase_time.version
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_product_purchase_time.cms_ppt_creat_time
     *
     * @mbg.generated
     */
    private Date cmsPptCreatTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_product_purchase_time.cms_ppt_update_time
     *
     * @mbg.generated
     */
    private Date cmsPptUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_product_purchase_time.product_id
     *
     * @mbg.generated
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_product_purchase_time.cms_ppt_rid
     *
     * @mbg.generated
     */
    private Integer cmsPptRid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_product_purchase_time.times
     *
     * @mbg.generated
     */
    private Integer times;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cms_product_purchase_time
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_product_purchase_time.cms_ppt_id
     *
     * @return the value of cms_product_purchase_time.cms_ppt_id
     *
     * @mbg.generated
     */
    public Integer getCmsPptId() {
        return cmsPptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_product_purchase_time.cms_ppt_id
     *
     * @param cmsPptId the value for cms_product_purchase_time.cms_ppt_id
     *
     * @mbg.generated
     */
    public void setCmsPptId(Integer cmsPptId) {
        this.cmsPptId = cmsPptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_product_purchase_time.version
     *
     * @return the value of cms_product_purchase_time.version
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_product_purchase_time.version
     *
     * @param version the value for cms_product_purchase_time.version
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_product_purchase_time.cms_ppt_creat_time
     *
     * @return the value of cms_product_purchase_time.cms_ppt_creat_time
     *
     * @mbg.generated
     */
    public Date getCmsPptCreatTime() {
        return cmsPptCreatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_product_purchase_time.cms_ppt_creat_time
     *
     * @param cmsPptCreatTime the value for cms_product_purchase_time.cms_ppt_creat_time
     *
     * @mbg.generated
     */
    public void setCmsPptCreatTime(Date cmsPptCreatTime) {
        this.cmsPptCreatTime = cmsPptCreatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_product_purchase_time.cms_ppt_update_time
     *
     * @return the value of cms_product_purchase_time.cms_ppt_update_time
     *
     * @mbg.generated
     */
    public Date getCmsPptUpdateTime() {
        return cmsPptUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_product_purchase_time.cms_ppt_update_time
     *
     * @param cmsPptUpdateTime the value for cms_product_purchase_time.cms_ppt_update_time
     *
     * @mbg.generated
     */
    public void setCmsPptUpdateTime(Date cmsPptUpdateTime) {
        this.cmsPptUpdateTime = cmsPptUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_product_purchase_time.product_id
     *
     * @return the value of cms_product_purchase_time.product_id
     *
     * @mbg.generated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_product_purchase_time.product_id
     *
     * @param productId the value for cms_product_purchase_time.product_id
     *
     * @mbg.generated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_product_purchase_time.cms_ppt_rid
     *
     * @return the value of cms_product_purchase_time.cms_ppt_rid
     *
     * @mbg.generated
     */
    public Integer getCmsPptRid() {
        return cmsPptRid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_product_purchase_time.cms_ppt_rid
     *
     * @param cmsPptRid the value for cms_product_purchase_time.cms_ppt_rid
     *
     * @mbg.generated
     */
    public void setCmsPptRid(Integer cmsPptRid) {
        this.cmsPptRid = cmsPptRid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_product_purchase_time.times
     *
     * @return the value of cms_product_purchase_time.times
     *
     * @mbg.generated
     */
    public Integer getTimes() {
        return times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_product_purchase_time.times
     *
     * @param times the value for cms_product_purchase_time.times
     *
     * @mbg.generated
     */
    public void setTimes(Integer times) {
        this.times = times;
    }
}