package com.cms.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table cms_rank
 */
public class CmsRank implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_rank.cms_rank_id
     *
     * @mbg.generated
     */
    private Integer cmsRankId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_rank.cms_rank_rid
     *
     * @mbg.generated
     */
    private Integer cmsRankRid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_rank.rank_name
     *
     * @mbg.generated
     */
    private String rankName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_rank.rank_info
     *
     * @mbg.generated
     */
    private String rankInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_rank.version
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_rank.cms_rank_creator
     *
     * @mbg.generated
     */
    private Integer cmsRankCreator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_rank.cms_rank_updator
     *
     * @mbg.generated
     */
    private Integer cmsRankUpdator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_rank.cms_rank_creat_time
     *
     * @mbg.generated
     */
    private Date cmsRankCreatTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_rank.cms_rank_update_time
     *
     * @mbg.generated
     */
    private Date cmsRankUpdateTime;

    /**
     * Database Column Remarks:
     *   0??¦Ä???
     *               1???????
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_rank.delete_sign
     *
     * @mbg.generated
     */
    private String deleteSign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cms_rank
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_rank.cms_rank_id
     *
     * @return the value of cms_rank.cms_rank_id
     *
     * @mbg.generated
     */
    public Integer getCmsRankId() {
        return cmsRankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_rank.cms_rank_id
     *
     * @param cmsRankId the value for cms_rank.cms_rank_id
     *
     * @mbg.generated
     */
    public void setCmsRankId(Integer cmsRankId) {
        this.cmsRankId = cmsRankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_rank.cms_rank_rid
     *
     * @return the value of cms_rank.cms_rank_rid
     *
     * @mbg.generated
     */
    public Integer getCmsRankRid() {
        return cmsRankRid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_rank.cms_rank_rid
     *
     * @param cmsRankRid the value for cms_rank.cms_rank_rid
     *
     * @mbg.generated
     */
    public void setCmsRankRid(Integer cmsRankRid) {
        this.cmsRankRid = cmsRankRid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_rank.rank_name
     *
     * @return the value of cms_rank.rank_name
     *
     * @mbg.generated
     */
    public String getRankName() {
        return rankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_rank.rank_name
     *
     * @param rankName the value for cms_rank.rank_name
     *
     * @mbg.generated
     */
    public void setRankName(String rankName) {
        this.rankName = rankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_rank.rank_info
     *
     * @return the value of cms_rank.rank_info
     *
     * @mbg.generated
     */
    public String getRankInfo() {
        return rankInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_rank.rank_info
     *
     * @param rankInfo the value for cms_rank.rank_info
     *
     * @mbg.generated
     */
    public void setRankInfo(String rankInfo) {
        this.rankInfo = rankInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_rank.version
     *
     * @return the value of cms_rank.version
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_rank.version
     *
     * @param version the value for cms_rank.version
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_rank.cms_rank_creator
     *
     * @return the value of cms_rank.cms_rank_creator
     *
     * @mbg.generated
     */
    public Integer getCmsRankCreator() {
        return cmsRankCreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_rank.cms_rank_creator
     *
     * @param cmsRankCreator the value for cms_rank.cms_rank_creator
     *
     * @mbg.generated
     */
    public void setCmsRankCreator(Integer cmsRankCreator) {
        this.cmsRankCreator = cmsRankCreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_rank.cms_rank_updator
     *
     * @return the value of cms_rank.cms_rank_updator
     *
     * @mbg.generated
     */
    public Integer getCmsRankUpdator() {
        return cmsRankUpdator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_rank.cms_rank_updator
     *
     * @param cmsRankUpdator the value for cms_rank.cms_rank_updator
     *
     * @mbg.generated
     */
    public void setCmsRankUpdator(Integer cmsRankUpdator) {
        this.cmsRankUpdator = cmsRankUpdator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_rank.cms_rank_creat_time
     *
     * @return the value of cms_rank.cms_rank_creat_time
     *
     * @mbg.generated
     */
    public Date getCmsRankCreatTime() {
        return cmsRankCreatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_rank.cms_rank_creat_time
     *
     * @param cmsRankCreatTime the value for cms_rank.cms_rank_creat_time
     *
     * @mbg.generated
     */
    public void setCmsRankCreatTime(Date cmsRankCreatTime) {
        this.cmsRankCreatTime = cmsRankCreatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_rank.cms_rank_update_time
     *
     * @return the value of cms_rank.cms_rank_update_time
     *
     * @mbg.generated
     */
    public Date getCmsRankUpdateTime() {
        return cmsRankUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_rank.cms_rank_update_time
     *
     * @param cmsRankUpdateTime the value for cms_rank.cms_rank_update_time
     *
     * @mbg.generated
     */
    public void setCmsRankUpdateTime(Date cmsRankUpdateTime) {
        this.cmsRankUpdateTime = cmsRankUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_rank.delete_sign
     *
     * @return the value of cms_rank.delete_sign
     *
     * @mbg.generated
     */
    public String getDeleteSign() {
        return deleteSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_rank.delete_sign
     *
     * @param deleteSign the value for cms_rank.delete_sign
     *
     * @mbg.generated
     */
    public void setDeleteSign(String deleteSign) {
        this.deleteSign = deleteSign;
    }
}