package com.cms.mapper;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import com.cms.pojo.CallInfoWithPhone;
import com.cms.pojo.CmsCallInfo;

@Mapper
public interface CmsCallInfoMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table cms_call_info
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer cmsCallId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table cms_call_info
	 *
	 * @mbg.generated
	 */
	int insert(CmsCallInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table cms_call_info
	 *
	 * @mbg.generated
	 */
	int insertSelective(CmsCallInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table cms_call_info
	 *
	 * @mbg.generated
	 */
	CmsCallInfo selectByPrimaryKey(Integer cmsCallId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table cms_call_info
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(CmsCallInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table cms_call_info
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(CmsCallInfo record);

	/**
	 * 
	 * @Title: listByPhoneAndTime
	 * @Description: 查询通话记录，时间位于参数2和参数3之间,拨打方或接收方的手机号为参数1。查询结果中的双方id被替换成双方手机号码。
	 * @param phone
	 * @param beginTime
	 * @param endTime
	 * @return
	 */
	List<CallInfoWithPhone> listByPhoneAndTime(String phone, Date beginTime, Date endTime);
}