package com.cms.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.cms.pojo.CmsCustomerAuth;
import com.cms.pojo.CmsCustomerCost;


@Mapper
public interface CmsCustomerAuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_customer_auth
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer cmsAuthId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_customer_auth
     *
     * @mbg.generated
     */
    int insert(CmsCustomerAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_customer_auth
     *
     * @mbg.generated
     */
    int insertSelective(CmsCustomerAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_customer_auth
     *
     * @mbg.generated
     */
    CmsCustomerAuth selectByPrimaryKey(Integer cmsAuthId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_customer_auth
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CmsCustomerAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_customer_auth
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CmsCustomerAuth record);
    
    CmsCustomerAuth selectByPhoneNum(String phoneNum);
    //通过账号，密码查询用户状态，并将状态返回
    String selectByIDAndPwd(CmsCustomerAuth record);
    //通过电话号码查询ridId
	int getRidId(String phoneNum);
	CmsCustomerAuth selectBycmsAuth(String phoneNum);

	List<CmsCustomerAuth> selectBycmsVersion();
	
	
	
}