package com.cms.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.cms.pojo.CmsCustomerCost;
import com.cms.pojo.CmsCustomerScore;

@Mapper
public interface CmsCustomerScoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_customer_score
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer cmsCsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_customer_score
     *
     * @mbg.generated
     */
    int insert(CmsCustomerScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_customer_score
     *
     * @mbg.generated
     */
    int insertSelective(CmsCustomerScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_customer_score
     *
     * @mbg.generated
     */
    CmsCustomerScore selectByPrimaryKey(Integer cmsCsId);
    void updateBybalance();
    List<CmsCustomerScore> selectBybalance();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_customer_score
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CmsCustomerScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_customer_score
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CmsCustomerScore record);
    
    /**
     * 
     * @Title: listCustomerScores
     * @Description: 根据客户手机号，查询该客户所有未过期的积分情况
     * @param phone
     * @return
     */
    List<CmsCustomerScore> listCustomerScores(String phone);
    
}