package com.cms.mapper;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.cms.pojo.CmsPaymentHistory;

@Mapper
public interface CmsPaymentHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_payment_history
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer cmsPhId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_payment_history
     *
     * @mbg.generated
     */
    int insert(CmsPaymentHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_payment_history
     *
     * @mbg.generated
     */
    int insertSelective(CmsPaymentHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_payment_history
     *
     * @mbg.generated
     */
    CmsPaymentHistory selectByPrimaryKey(Integer cmsPhId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_payment_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CmsPaymentHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_payment_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CmsPaymentHistory record);

	List<CmsPaymentHistory> getInfo(int ridId,Date beginTime,Date endTime);
}