package com.cms.mapper;

import org.apache.ibatis.annotations.Mapper;

import com.cms.pojo.CmsProductPurchaseTime;

@Mapper
public interface CmsProductPurchaseTimeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_product_purchase_time
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer cmsPptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_product_purchase_time
     *
     * @mbg.generated
     */
    int insert(CmsProductPurchaseTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_product_purchase_time
     *
     * @mbg.generated
     */
    int insertSelective(CmsProductPurchaseTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_product_purchase_time
     *
     * @mbg.generated
     */
    CmsProductPurchaseTime selectByPrimaryKey(Integer cmsPptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_product_purchase_time
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CmsProductPurchaseTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_product_purchase_time
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CmsProductPurchaseTime record);
}