package com.cms.mapper;

import org.apache.ibatis.annotations.Mapper;

import com.cms.pojo.CmsScoreWeight;

@Mapper
public interface CmsScoreWeightMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_score_weight
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer cmsSwId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_score_weight
     *
     * @mbg.generated
     */
    int insert(CmsScoreWeight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_score_weight
     *
     * @mbg.generated
     */
    int insertSelective(CmsScoreWeight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_score_weight
     *
     * @mbg.generated
     */
    CmsScoreWeight selectByPrimaryKey(Integer cmsSwId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_score_weight
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CmsScoreWeight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_score_weight
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CmsScoreWeight record);
}